### ISSUE TITLE
Create a reliable and current TaskList filter gem for HTML::PIpeline

### ISSUE THREAD

**Issue by ac21** [codetree/html-pipeline-task_list#2]
## Background
Create a reliable and current TaskList filter gem for HTML::PIpeline

Tasks
- [x] create initial `HTML::Pipeline::TaskList` based on `github/task_list`
- [x] refactor to replace coffeescript with javascript
- [x] add javascript based testing
- [x] add rubocop scanning
- [x] automate build process
